#!/bin/bash

# Get current timestamp
TIMESTAMP=$(date +"%Y-%m-%d_%H.%M.%S")

# Create output directory with timestamp
OUT_DIR="output/output_$TIMESTAMP"
mkdir -p $OUT_DIR $OUT_DIR/tmp
export OUT_DIR

# Activate conda environment
eval "$(conda shell.bash hook)"

# Declare an array of tools to install
declare -a TOOLS=(
"picard"
"bcftools"
"pandas"
)

# Check if conda is installed
if ! command -v conda &> /dev/null
then
    echo "conda could not be found"
    exit
fi

# Check if seq-ann environment exists. If not, create it and install tools.
if ! conda env list | grep -q "seq-ann"
then
    conda config --add channels defaults
    conda config --add channels bioconda
    conda config --add channels conda-forge
    conda config --set channel_priority strict
    conda create --name seq-ann python==3.8.2 -y
    conda activate seq-ann
    for i in "${TOOLS[@]}"
    do
        conda install -y "$i"
    done
    conda deactivate
fi

##pull the vep docker image with singularity
##Here singularity module on Minerva is loaded but singularity installation might be necessary for other users
mkdir ../anno
cd ../anno

ml singularity/3.6.4
singularity pull --name vep_109.sif docker://ensemblorg/ensembl-vep:release_109.3

mkdir vep_data

##The cache has already been downloaded on Minerva, so I skipped the next command, instead I copied the cache (homo_sapiens folder) and fasta file(s) to /local/ece/anno/vep_data
#singularity exec vep.sif INSTALL.pl -c /local/ece/anno/vep_data -a cf -s homo_sapiens -y GRCh38

##Create two folders for input and output files
mkdir vep_data/input
mkdir vep_data/output
