#!/bin/bash

# Get current timestamp
TIMESTAMP=$(date +"%Y-%m-%d_%H.%M.%S")

# Create output directory with timestamp
OUT_DIR="output/output_$TIMESTAMP"
mkdir -p $OUT_DIR $OUT_DIR/tmp
export OUT_DIR

# Activate conda environment
eval "$(conda shell.bash hook)"

# Declare an array of tools to install
declare -a TOOLS=(
"ensembl-vep=109.3"
"picard"
"bcftools"
"pandas"
)

# Check if conda is installed
if ! command -v conda &> /dev/null
then
    echo "conda could not be found"
    exit
fi

# Check if seq-ann environment exists. If not, create it and install tools.
if ! conda env list | grep -q "seq-ann"
then
    conda config --add channels defaults
    conda config --add channels bioconda
    conda config --add channels conda-forge
    conda config --set channel_priority strict
    conda create --name seq-ann python==3.8.2 -y
    conda activate seq-ann
    for i in "${TOOLS[@]}"
    do
        conda install -y "$i"
    done
    conda deactivate
fi

# Setup VEP GRCh38 reference genome
# vep_install -a cf -s homo_sapiens -y GRCh38
